name: picovoice_demo
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  avatar_glow: ^2.0.1
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.0
  freezed_annotation: ^0.14.2
  hooks_riverpod: ^1.0.0-dev.5
  path_provider: ^2.0.2
  picovoice: ^1.1.8
  porcupine: ^1.9.13
  rhino: ^1.6.10
  state_notifier: ^0.7.0

dev_dependencies:
  build_runner: ^2.0.5
  flutter_test:
    sdk: flutter
  freezed: ^0.14.2

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/picovoice/android/
    - assets/picovoice/ios/
